version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Build the Node.js app using your Dockerfile
    container_name: zephyrnet_backend
    working_dir: /app
    volumes:
      - ./backend:/app  # Mounts the local backend directory to the container
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=db
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_NAME=zephyrnet_chat
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_jwt_secret  # Replace with a strong secret for authentication
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    command: "npm start"  # Adjust based on your start command

  db:
    image: postgres:13  # PostgreSQL version
    container_name: zephyrnet_db
    environment:
      POSTGRES_DB: zephyrnet_chat
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data

  redis:
    image: redis:6
    container_name: zephyrnet_redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: zephyrnet_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount custom Nginx config (optional)
    depends_on:
      - backend

volumes:
  pgdata:  # Volume for PostgreSQL data persistence
