name: Deploy to Cloud

on:
  push:
    branches: [ main ]  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker and Docker Compose
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 4: Build and push Docker images
      - name: Build and push Docker images
        run: docker-compose -f docker-compose.yml up --build -d
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
          AZURE_REGION: ${{ secrets.AZURE_REGION }}

      # Step 5: Deploy to Azure Web App
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ethereal-link  # Name of your Azure Web App
          slot-name: production    # Deployment slot (could be 'staging' or 'production')
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Publish profile for Azure Web App
